name: Build Moonlight-Switch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Remove useless fonts
      run: rm -rf ./resources/font
      
    - name: Update image
      run: dkp-pacman -Syyu
        
    - name: Run build
      run: make -j8

    - name: Upload Moonlight-Switch.nro
      uses: actions/upload-artifact@master
      with:
        name: Moonlight-Switch
        path: Moonlight-Switch.nro

    - name: Upload Moonlight-Switch.elf
      uses: actions/upload-artifact@master
      with:
        name: Debug.elf
        path: Moonlight-Switch.elf
